#!/bin/sh

while true; do
    sh -c "$*"
    exitcode=$?
    [ ${exitcode} -eq 0 ] && {
        echo "Program terminated noramlly." >&2
        break
    }
    echo "Exited with: ${exitcode}, wait 2 seconds to retry" >&2
    sleep 2
done
