#!/bin/sh

start_path="$(pwd)"
script="$1"
if ! [ -f "${script}" ]; then
    echo "\"${script}\" - file not found" >&2
    exit 1
fi
shift
base="$(basename "${script}" .cc)"

if [ -d "/dev/shm" ]; then
    # prefer memory
    temp="$(mktemp -p /dev/shm -d)"
else
    temp="$(mktemp -d)"
fi

if which "clang++" >/dev/null 2>&1; then
    # prefer clang
    CXX="clang++"
fi

if [ "${CXXFLAGS}" = "" ]; then
    CXXFLAGS="-pipe -pedantic -Wall -Wextra -O3"
fi

if [ "${LDFLAGS}" = "" ]; then
    # link glibc
    LDFLAGS="-lm -lrt -lpthread"
fi

printf "+ ${CXX} ${CXXFLAGS} -o \"${temp}/${base}\" \"${script}\" ${LDFLAGS}\n"
if ! ${CXX} ${CXXFLAGS} -o "${temp}/${base}" "${script}" ${LDFLAGS}; then
    rm -r "${temp}"
    exit 1
fi

(cd "${temp}" && "./${base}" "$@")

rm -r "${temp}"
