#!/bin/sh

start_path="$(pwd)"
script="$1"
if ! [ -f "${script}" ]; then
    echo "\"${script}\" - file not found" >&2
    exit 1
fi
shift
base="$(basename "${script}" .cc)"

# prefer memory
if [ -d "/dev/shm" ]; then
    temp="$(mktemp -p /dev/shm -d)"
elif [ -d "/run/shm" ]; then
    temp="$(mktemp -p /run/shm -d)"
else
    temp="$(mktemp -d)"
fi

if [ -z "${CXX}" ]; then
    if CXX="$(command -v g++)"; then
        :
    elif CXX="$(command -v clang++)"; then
        :
    fi
fi

if [ "${CXXFLAGS}" = "" ]; then
    CXXFLAGS="-pipe -pedantic -Wall -Wextra -O3"
fi

if [ "${LDFLAGS}" = "" ]; then
    # try link common libs
    LDFLAGS="-lm -lrt -lpthread -ldl"
fi

echo "+ ${CXX} ${CXXFLAGS} -o \"${temp}/${base}\" \"${script}\" ${LDFLAGS}"
if ! ${CXX} ${CXXFLAGS} -o "${temp}/${base}" "${script}" ${LDFLAGS}; then
    rm -r "${temp}"
    exit 1
fi

(cd "${temp}" && "./${base}" "$@")

rm -r "${temp}"
