#!/bin/sh

start_path="$(pwd)"
script="$1"
if ! [ -f "${script}" ]; then
    echo "\"${script}\" - file not found" >&2
    exit 1
fi
shift
base="$(basename "${script}" .cc)"

if [ -d "/dev/shm" ]; then
    # prefer memory
    temp="$(mktemp -p /dev/shm -d)"
else
    temp="$(mktemp -d)"
fi

clang++ -O3 -pedantic -Wall -Wextra ${CXXFLAGS} ${LDFLAGS} "${script}" -o "${temp}/${base}" \
    -lm -lrt -lpthread || {
    rm -r "${temp}"
    exit 1
}

cd "${temp}"
"./${base}" "$@"
cd "${start_path}"
rm -r "${temp}"
