#!/bin/sh

start_path="$(pwd)"
script="$1"
if ! [ -f "${script}" ]; then
    echo "\"${script}\" - file not found" >&2
    exit 1
fi
shift
base="$(basename "${script}" .cc)"

temp="$(mktemp -d)"
clang++ -O3 -pedantic -Wall -Wextra ${CXXFLAGS} ${LDFLAGS} "${script}" -o "${temp}/${base}" || {
    rmdir "${temp}"
    exit 1
}

cd "${temp}"
"./${base}" "$@"
cd "${start_path}"
rm -r "${temp}"
