#!/bin/sh

script="$1"
if ! [ -f "${script}" ]; then
	echo "\"${script}\" - file not found" >&2
	exit 1
fi
shift
base="$(basename "${script}" .c)"

# prefer memory
if [ -d "/dev/shm" ]; then
	temp="$(mktemp -p /dev/shm -d)"
elif [ -d "/run/shm" ]; then
	temp="$(mktemp -p /run/shm -d)"
else
	temp="$(mktemp -d)"
fi

if [ -z "${CC}" ]; then
	if CC="$(command -v gcc)"; then
		:
	elif CC="$(command -v clang)"; then
		:
	fi
fi

if [ -z "${CFLAGS}" ]; then
	CFLAGS="-pipe -pedantic -Wall -Wextra -Werror -O3"
fi

if [ -z "${LDFLAGS}" ]; then
	# try link common libs
	LDFLAGS="-lm -lrt -lpthread -ldl"
fi

echo "+ ${CC} ${CFLAGS} -o \"${temp}/${base}\" \"${script}\" ${LDFLAGS}"
if ! ${CC} ${CFLAGS} -o "${temp}/${base}" "${script}" ${LDFLAGS}; then
	rm -r "${temp}"
	exit 1
fi

(cd "${temp}" && "./${base}" "$@")

rm -r "${temp}"
