#!/bin/sh

SCRIPT="$1"
if ! [ -f "${SCRIPT}" ]; then
	echo "\"${SCRIPT}\" - file not found" >&2
	exit 1
fi
shift
BASENAME="$(basename "${SCRIPT}" .c)"
TEMPDIR="$(mktemp -d)"

if [ ! -d "${TEMPDIR}" ]; then
	echo "failed to create \"${TEMPDIR}\""
	exit 1
fi

if [ -z "${CC}" ]; then
	if command -v "gcc" >/dev/null 2>&1; then
		CC="$(command -v gcc)"
	elif command -v "clang" >/dev/null 2>&1; then
		CC="$(command -v clang)"
	fi
fi

if [ -z "${CFLAGS}" ]; then
	CFLAGS="-pipe -pedantic -Wall -Wextra -Werror -O3"
fi

if [ -z "${LDFLAGS}" ]; then
	# try link common libs
	LDFLAGS="-lm -lrt -lpthread -ldl"
fi

echo "+ ${CC} ${CFLAGS} -o \"${TEMPDIR}/${BASENAME}\" \"${SCRIPT}\" ${LDFLAGS}"
if ! ${CC} ${CFLAGS} -o "${TEMPDIR}/${BASENAME}" "${SCRIPT}" ${LDFLAGS}; then
	rm -r "${TEMPDIR}"
	exit 1
fi

(cd "${TEMPDIR}" && "./${BASENAME}" "$@")

rm -r "${TEMPDIR}"
