#!/bin/sh

if which clang++ >/dev/null 2>&1 && which lli >/dev/null 2>&1; then
    clang++ -O3 -pedantic -Wall -Wextra -c -emit-llvm -o - ${CFLAGS} "$1" | lli -
    exit 0
fi

temp="$(mktemp -d)"
${CXX:-g++} -pipe -g -O2 -DNDEBUG -std=c++17 ${CFLAGS} ${LDFLAGS} $1 -o "${temp}/a.out" || {
    rmdir "${temp}"
    exit 1
}
shift
"${temp}/a.out" $*
rm -r "${temp}"
