#!/bin/sh

log() {
    if [ "$USE_SYSLOG" = 1 ]; then
        logger -t "keepd[$$]" "$*"
    else
        echo "$(date -Is) keepd[$$]: $*"
    fi
}

if [ ! -t 0 ]; then
    USE_SYSLOG=1
fi

invoke_command() {
    "$@" &
    PID="$!"
    log "started \"$*\" in \"$PWD\", pid ${PID}"
    wait "${PID}"
    STATUS="$?"
    log "${PID} exited with ${STATUS}"
    unset PID
    unset STATUS
}

clean_exit() {
    if [ -n "${PID}" ]; then
        log "killing ${PID}"
        kill "${PID}"
        unset PID
    fi
    exit 0
}

trap "USE_SYSLOG=1" HUP
trap "clean_exit || true" EXIT INT QUIT TERM

while true; do
    invoke_command "$@"
    sleep 10
done
