#!/bin/sh

if [ $(whoami) != root ]; then
    sudo "$0" $*
    exit $?
fi

runApt() {
	echo ">>> $1"
	if ! apt-get $2; then
		echo "Failed!"
		exit 1
	fi
}

purgeConf() {
	list="$(dpkg -l | grep ^rc | awk '{print $2}')"
	if [ ! -z "$list" ]; then
		echo "$list" | xargs dpkg --purge
	fi
}

runApt "Update catalog..." "update"
runApt "Fix missing..." "install -f -y"
runApt "Upgrade package..." "dist-upgrade -y"
runApt "Remove redudant..." "autoremove -y"
runApt "Clean archive..." "autoclean"
echo ">>> Purge configuration..."
purgeConf

echo ">>> Refresh snaps..."
snap refresh

echo ">>> Remove disabled snaps..."
snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done
