#!/bin/sh

if [ "$(whoami)" != "root" ]; then
    if [ -n "$(which sudo)" ]; then
		echo "\$ sudo $0 $*"
		sudo $0 $*
	else
		echo "\$ su -c "$0 $*" root"
		su -c "$0 $*" root
	fi
    exit $?
fi

RED='\e[91m'
YELLOW='\e[93m'
CYAN='\e[96m'
RESET='\e[0m'

showProgress() {
	echo "${CYAN}>>> $1...${RESET}"
}

tryRun() {
	if ! $*; then
		echo "${RED}Failed! code: $?${RESET}"
		exit 1
	fi
}

maintenanceApt() {
	showProgress "Update catalog"
	tryRun apt-get update
	showProgress "Fix missing"
	tryRun apt-get install -f -y
	showProgress "Upgrade package"
	tryRun apt-get dist-upgrade -y
	showProgress "Remove redudant"
	tryRun apt-get autoremove -y
	showProgress "Clean archive"
	tryRun apt-get autoclean
	showProgress "Purge configuration"
	dpkg -l | grep ^rc | awk '{print $2}' |
		while read packagename; do
			[ -n "$packagename" ] &&
				tryRun dpkg --purge "$packagename"
		done
}

maintenanceSnap() {
	showProgress "Refresh snaps"
	snap refresh

	showProgress "Remove disabled snaps"
	snap list --all | awk '/disabled/{print $1, $3}' |
		while read snapname revision; do
			tryRun snap remove "$snapname" --revision="$revision"
		done
}

if [ -n "$(which apt-get)" ]; then
	maintenanceApt
else
	echo "${YELLOW}apt-get command not found${RESET}"
fi

if [ -n "$(which snap)" ]; then
	maintenanceSnap
else
	echo "${YELLOW}snap command not found${RESET}"
fi
