#!/bin/sh

if [ $(whoami) != root ]; then
    if [ -n $(which sudo) ]; then
		echo "\$ sudo $0 $*"
		sudo $0 $*
	else
		echo "\$ su -c "$0 $*" root"
		su -c "$0 $*" root
	fi
    exit $?
fi

SWAPS="$(tail -n +2 /proc/swaps | awk '{print $1}')"

[ -z "$SWAPS" ] && exit 0

for SWAP in $SWAPS; do
    echo "- $SWAP"
    swapoff "$SWAP"
done

for SWAP in $SWAPS; do
    echo "+ $SWAP"
    swapon "$SWAP"
done

