#!/bin/sh

log() {
    printf "$(date -Iseconds) $*\n" >&2
}

while true; do
    sh -c "$*"
    exitcode="$?"
    if [ "${exitcode}" = "0" ]; then
        log "Program terminated noramlly."
        break
    fi
    log "Exited with: ${exitcode}, wait 60 seconds to retry"
    sleep 60
done
