#!/bin/sh

echo 0 | sudo tee /sys/block/sda/queue/iosched/low_latency
echo 4096 | sudo tee /sys/block/sda/queue/nr_requests
echo 512 | sudo tee /sys/block/sda/queue/read_ahead_kb

#echo performance | sudo tee \
#    /sys/devices/system/cpu/cpufreq/policy0/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy1/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy2/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy3/scaling_governor

#sudo intel_gpu_frequency -m

