#!/bin/sh

if [ $(whoami) != root ]; then
    sudo "$0" $*
    exit $?
fi

echo ">>> Applying tweaks..."
echo 0 > /sys/block/sda/queue/iosched/low_latency
echo 4096 > /sys/block/sda/queue/nr_requests
echo 512 > /sys/block/sda/queue/read_ahead_kb

#echo performance | tee \
#    /sys/devices/system/cpu/cpufreq/policy0/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy1/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy2/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy3/scaling_governor \
#    > /dev/null

#intel_gpu_frequency -m
