#!/bin/sh

if [ "$(whoami)" != "root" ]; then
    if [ -n "$(which sudo)" ]; then
		echo "\$ sudo $0 $*"
		sudo $0 $*
	else
		echo "\$ su -c "$0 $*" root"
		su -c "$0 $*" root
	fi
    exit $?
fi

if [ -t 1 ] && [ "$(tput colors)" -ge 16 ] 2>/dev/null; then
    RED="$(tput setaf 9)"
    GREEN="$(tput setaf 10)"
    YELLOW="$(tput setaf 11)"
    BLUE="$(tput setaf 12)"
    MAGENTA="$(tput setaf 13)"
    CYAN="$(tput setaf 14)"
    RESET="$(tput sgr0)"
fi

write() {
    if [ -f "$1" ] && [ -w "$1" ]; then
        echo "write ${MAGENTA}$1${RESET}: ${CYAN}$2${RESET}"
        echo "$2" > "$1"
    fi
}

echo ">>> Applying tweaks..."
for block in sda sdb sdc sdd sde sdf; do
    if [ -d "/sys/block/$block" ] &&
        [ "$(cat /sys/block/$block/queue/rotational)" = "1" ]; then
        write /sys/block/$block/queue/iosched/low_latency 0
        write /sys/block/$block/queue/nr_requests 4096
        write /sys/block/$block/queue/read_ahead_kb 512
    fi
done

#echo performance | tee \
#    /sys/devices/system/cpu/cpufreq/policy0/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy1/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy2/scaling_governor \
#    /sys/devices/system/cpu/cpufreq/policy3/scaling_governor \
#    > /dev/null

#intel_gpu_frequency -m
