#!/bin/sh

if [ "$(whoami)" != "root" ]; then
    if [ -n "$(which sudo)" ]; then
		echo "\$ sudo $0 $*"
		sudo $0 $*
	else
		echo "\$ su -c "$0 $*" root"
		su -c "$0 $*" root
	fi
    exit $?
fi

if [ -t 1 ] && [ "$(tput colors)" -ge 16 ] 2>/dev/null; then
    RED="$(tput setaf 9)"
    GREEN="$(tput setaf 10)"
    YELLOW="$(tput setaf 11)"
    BLUE="$(tput setaf 12)"
    MAGENTA="$(tput setaf 13)"
    CYAN="$(tput setaf 14)"
    RESET="$(tput sgr0)"
fi

enabled=$(cat /sys/module/zswap/parameters/enabled)
[ $enabled = Y ] || exit 2
memtotal=$(cat /proc/meminfo | grep '^MemTotal:' | awk '{print $2}')
page_size=$(getconf PAGE_SIZE)
compressor=$(cat /sys/module/zswap/parameters/compressor)
zpool=$(cat /sys/module/zswap/parameters/zpool)
max_pool_percent=$(cat /sys/module/zswap/parameters/max_pool_percent)
max_pool_size=$(expr $memtotal / 1024 "*" $max_pool_percent / 100)
while true; do
    pool_total_size=$(cat /sys/kernel/debug/zswap/pool_total_size)
    pool_total_size=$(expr $pool_total_size / 1048576)
    [ $pool_total_size -gt $max_pool_size ] && pool_total_size=$max_pool_size
    pool_usage=$(expr $pool_total_size "*" 100 / $max_pool_size)
    stored_size=$(cat /sys/kernel/debug/zswap/stored_pages)
    stored_size=$(expr $stored_size "*" $page_size / 1048576)
    written_back_size=$(cat /sys/kernel/debug/zswap/written_back_pages)
    written_back_size=$(expr $written_back_size "*" $page_size / 1048576)
    reject_compress_poor=$(cat /sys/kernel/debug/zswap/reject_compress_poor)
    reject_compress_poor=$(expr $reject_compress_poor "*" $page_size / 1048576)
    [ $stored_size -eq 0 ] && compress_ratio=0 ||
        compress_ratio=$(expr $pool_total_size "*" 100 / $stored_size)
    buffer="$(date)
${MAGENTA}zswap${RESET}: loaded using pool ${CYAN}${compressor}${RESET}/${CYAN}${zpool}${RESET}

${MAGENTA}pool_total_size${RESET}:      ${YELLOW}$pool_total_size MB${RESET} / ${CYAN}$max_pool_size MB${RESET} (${YELLOW}${pool_usage}%${RESET})
${MAGENTA}stored_size${RESET}:          ${YELLOW}$stored_size MB${RESET}
${MAGENTA}written_back_size${RESET}:    ${YELLOW}$written_back_size MB${RESET}
${MAGENTA}reject_compress_poor${RESET}: ${YELLOW}$reject_compress_poor MB${RESET}
${MAGENTA}compress_ratio${RESET}:       ${YELLOW}${compress_ratio}%${RESET}
"
    clear; echo -n "${buffer}"
    sleep 5
done
